import React from 'react'

const Exp = () => {
  const exp=[
    {
      id:1,
      tittle:"Senior developor",
      company:"OTis",
      date:"11 Dec 2024",
      description:" Otis Worldwide Corporation (branded as the Otis Elevator Company, its former legal name) is an American company that develops, manufactures and markets elevators, escalators, moving walkways, and related equipment.Based in Farmington, Connecticut, U.S., Otis is the world's largest manufacturer of vertical transportation systems, principally focusing on elevators, moving walkways, and escalators.[2] The company pioneered the development of the safety elevator, invented by Elisha Otis in 1852, which used a special mechanism to lock the elevator car in place should the hoisting ropes fail.The Otis Elevator Company was acquired by United Technologies in 1976, but it was spun off as an independent company 44 years later in April 2020 as Otis Worldwide Corporation.[3][4]Its slogan is Made to move you",
    },
    {
      id:1,
      tittle:"Senior devp",
      company:"IBM",
      date:"24 Dec 2002",
    description:"International Business Machines Corporation (using the trademark IBM), nicknamed Big Blue,[6] is an American multinational technology company headquartered in Armonk, New York and present in over 175 countries.[7][8] IBM is the largest industrial research organization in the world, with 19 research facilities across a dozen countries, having held the record for most annual U.S. patents generated by a business for 29 consecutive years from 1993 to 2021.IBM was founded in 1911 as the Computing-Tabulating-Recording Company (CTR), a holding company of manufacturers of record-keeping and measuring systems. It was renamed International Business Machines in 1924 and soon became the leading manufacturer of punch-card tabulating systems. During the 1960s and 1970s, the IBM mainframe, exemplified by the System/360, was the world's dominant computing platform, with the company producing 80 percent of computers in the U.S. and 70 percent of computers worldwide",
    }
  ]
  return (
    <div className='container br p-5'>
       <h1>A Senior Developer is an experienced and highly skilled professional responsible for overseeing and guiding the development of software projects. They play a crucial role in the software development lifecycle, from initial planning and design to implementation, testing, and deployment. Their expertise and leadership help ensure the success of projects and the development of junior team members.</h1>
      {
        exp.map((e)=>{
        return (
          <div className='row'>
            <div className='col-lg-6 p-3'>
              <h5>{e.tittle}</h5>
              <h6>{e.company}</h6>
              <h3>{e.date}</h3>
              </div>
              <div className='col-lg-6 br'>{e.description} </div>
            </div>

        )
        
        }
      )
      }
    </div>
  )
}

export default Exp
